# Generated by Django 3.2.5 on 2022-01-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tag_line', models.CharField(max_length=250)),
                ('slider_img', models.ImageField(height_field='static/assets/img/hero-carousel', upload_to=None)),
            ],
        ),
    ]
