# Generated by Django 3.2.5 on 2022-01-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almehdi_Quran_Center', '0002_auto_20220105_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=150)),
                ('t_role', models.CharField(max_length=250)),
                ('t_fb_username', models.CharField(max_length=50)),
                ('t_tiwitter_username', models.CharField(max_length=50)),
                ('t_insta_username', models.CharField(max_length=50)),
                ('t_img', models.ImageField(upload_to='static/assets/img/team')),
            ],
        ),
        migrations.AlterField(
            model_name='enroll',
            name='fullname',
            field=models.CharField(default='name', max_length=150),
        ),
    ]
