# Generated by Django 3.2.5 on 2022-01-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almehdi_Quran_Center', '0003_auto_20220106_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='t_tiwitter_username',
            new_name='t_twitter_username',
        ),
    ]
