# Generated by Django 3.2.5 on 2022-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almehdi_Quran_Center', '0005_tesmonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(default='subject', max_length=150)),
                ('msg', models.CharField(default='msg', max_length=590)),
            ],
        ),
    ]
